spring.application.name=Ecom-application

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ecom
spring.datasource.username=root
spring.datasource.password=Bhiwani@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always